### PR TITLE
feat(front): Add keypoints on video

### LINKED ISSUE #215: Keypoint annotation in video frame (single)

### PR DESCRIPTION
**Pull request by timothee-LJN**
## Issue

Fixes #215 

## Description

To allow keypoints on video, the data model has been made more generic. The documentation has been updated for further details : 

- `keyPoints` and `boxes` now have a `tracklet_id` which allow to build `trackletWithItems` 
- `tracklet` now have only a start, and end and an ID
- all videos APIs have been refactored to be more generic

### CODE REVIEW

**Review by ulysse-bonneau — APPROVED** [review]

**Comment by BertrandRenault** [comment]
@timothee-LJN 
I made some minor changes to front: 
- remove previous convert for old format ( aka "obj.boxes = obj.track[0]?.boxes" )
- add displayControl and displayedKeypoints for keypoints. I put it at the same place it was, just after call to api.getDatasetItem
   --> I'm not sure it's the right place to do that.
   --> after save, the round dot showing "is_key" is not drawn anymore, and the keypoints is not drawn if the starting frame is not 0
   
  Could we discuss about this when you have some time please ?

**Comment by timothee-LJN** [comment]
> add displayControl and displayedKeypoints for keypoints. I put it at the same place it was, just after call to api.getDatasetItem 

I've refactored that and remove some useless code (that I forgot to remove)

**Comment by BertrandRenault** [comment]
>   --> after save, the round circles showing "is_key" are not drawn anymore, and the keypoints is not drawn if the starting frame is not 0
Last commit fix the "keypoints is not drawn if the starting frame is not 0" issue (keyppoints require deep copy, I used structuredClone fct)
But there is still the issue with round circles showing keys whom are not shown anymore

**Comment by BertrandRenault** [comment]
>  --> after save, the round circles showing "is_key" are not drawn anymore
Fixed

**Pull request merged**
